import json
import random
from typing import Any, Dict, List, Optional

_QCLASS_FIRST = {"sigma": "exists", "pi": "forall"}
_QDIMACS_QUANTIFIER = {"exists": "e", "forall": "a"}


def _require_positive_int(value: int, name: str) -> None:
    if not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")


def _derive_block_sizes(level: int, num_vars: int, variables_per_block: Optional[List[int]]) -> List[int]:
    if variables_per_block is not None:
        if len(variables_per_block) != level:
            raise ValueError("variables_per_block must have length equal to level")
        if any((not isinstance(v, int) or v <= 0) for v in variables_per_block):
            raise ValueError("variables_per_block entries must be positive integers")
        if sum(variables_per_block) != num_vars:
            raise ValueError("variables_per_block must sum to num_vars")
        return list(variables_per_block)

    base = num_vars // level
    remainder = num_vars % level
    if base == 0:
        raise ValueError("num_vars must be at least level")
    sizes = []
    for idx in range(level):
        sizes.append(base + (1 if idx < remainder else 0))
    return sizes


def _generate_clauses(
    num_vars: int,
    num_clauses: int,
    clause_size: int,
    rng: random.Random,
) -> List[List[int]]:
    if clause_size > num_vars:
        raise ValueError("clause_size must be <= num_vars")
    clauses: List[List[int]] = []
    var_ids = list(range(1, num_vars + 1))
    for _ in range(num_clauses):
        chosen = rng.sample(var_ids, clause_size)
        clause = []
        for var in chosen:
            lit = var if rng.choice([True, False]) else -var
            clause.append(lit)
        clauses.append(clause)
    return clauses


def generate_qbf_problem(
    *,
    level: int,
    qclass: str,
    num_vars: int,
    num_clauses: int,
    clause_size: int = 3,
    seed: Optional[int] = None,
    variables_per_block: Optional[List[int]] = None,
) -> Dict[str, Any]:
    _require_positive_int(level, "level")
    _require_positive_int(num_vars, "num_vars")
    _require_positive_int(num_clauses, "num_clauses")
    _require_positive_int(clause_size, "clause_size")
    if qclass not in _QCLASS_FIRST:
        raise ValueError("qclass must be 'sigma' or 'pi'")
    if num_vars < level:
        raise ValueError("num_vars must be >= level")

    block_sizes = _derive_block_sizes(level, num_vars, variables_per_block)
    quantifier = _QCLASS_FIRST[qclass]
    next_var = 1
    blocks: List[Dict[str, Any]] = []
    for size in block_sizes:
        vars_in_block = list(range(next_var, next_var + size))
        blocks.append({"quantifier": quantifier, "variables": vars_in_block})
        next_var += size
        quantifier = "forall" if quantifier == "exists" else "exists"

    rng = random.Random(seed)
    clauses = _generate_clauses(num_vars, num_clauses, clause_size, rng)

    return {
        "format_version": 1,
        "level": level,
        "class": qclass,
        "num_vars": num_vars,
        "num_clauses": num_clauses,
        "clause_size": clause_size,
        "seed": seed,
        "quantifier_blocks": blocks,
        "clauses": clauses,
    }


def to_qdimacs(problem: Dict[str, Any]) -> str:
    num_vars = problem["num_vars"]
    num_clauses = problem["num_clauses"]
    lines = ["c Generated by ph_iq", f"p cnf {num_vars} {num_clauses}"]
    for block in problem["quantifier_blocks"]:
        quant = _QDIMACS_QUANTIFIER[block["quantifier"]]
        vars_part = " ".join(str(v) for v in block["variables"])
        lines.append(f"{quant} {vars_part} 0")
    for clause in problem["clauses"]:
        clause_part = " ".join(str(lit) for lit in clause)
        lines.append(f"{clause_part} 0")
    return "\n".join(lines) + "\n"


def to_json(problem: Dict[str, Any]) -> str:
    return json.dumps(problem, indent=2, sort_keys=True) + "\n"
